name: Readme Generator
on:
  schedule: [{ cron: '0 0 * * *' }]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🐈‍⬛ Left
        uses: lowlighter/metrics@latest
        with:
          filename: assets/left.svg
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, starts, achievements
          plugin_isocalendar: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_achievements: yes
          plugin_achievements_display: compact
          token: ${{ secrets.GH_TOKEN }}

      - name: 🐈‍⬛ Rihgt
        uses: lowlighter/metrics@latest
        with:
          config_order: anilist, steam
          filename: assets/right.svg
          base: ''
          plugin_anilist_user: 'canisminor1990'
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 3
          plugin_anilist_limit_characters: 22
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: '076561198054835207'
          plugin_steam_achievements_limit: 1
          token: ${{ secrets.GH_TOKEN }}

      - name: ⏰ Waka
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: 'False'
          SHOW_PROJECTS: 'False'
          SHOW_LANGUAGE: 'False'
          SHOW_TIMEZONE: 'False'
          SHOW_EDITORS: 'False'
          SHOW_LANGUAGE_PER_REPO: 'False'
          SHOW_SHORT_INFO: 'False'
          SHOW_LOC_CHART: 'False'
          SHOW_TOTAL_CODE_TIME: 'False'
          SHOW_PROFILE_VIEWS: 'False'
          SHOW_DAYS_OF_WEEK: 'False'
          SYMBOL_VERSION: 3
