name: Waka Readme

on:
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{cron: "0 16 * * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK: "False" 
